[package]
name = "pf_sandbox"
version = "0.1.1"
authors = ["Rukai <rubickent@gmail.com>"]
description = "A platform fighter sandbox featuring a character editor tightly integrated with gameplay."
license = "GPL-3.0"
repository = "https://github.com/rukai/pf_sandbox"
homepage = "https://pfsandbox.net"
keywords = ["pf", "sandbox", "platform", "fighter", "game"]
categories = ["games", "game-engines"]

[dependencies]
bincode = "1"
byteorder = "1"
chrono = { version = "0.4", features = ["serde"] }
enum_traits = "0.3"
enum_traits_macros = "2.0"
env_logger = "0.5"
getopts = "0.2"
human-panic = { git = "https://github.com/rukai/human-panic", branch = "native_window", features = ["gui"] }
gilrs = { git = "https://gitlab.com/gilrs-project/gilrs" }
libusb = "0.3"
log = "0.4"
lyon = "0.11"
matches = "0.1"
rand = "0.5"
reqwest = "0.8"
rust-crypto = "0.2"
dirs = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
treeflection = "0.1"
treeflection_derive = "0.3"
uuid = { version = "0.6.0-beta", features = ["v4", "serde"] }
winit = { git = "https://github.com/tomaka/winit" } # Needed on all builds, game logic is dependent on VirtualKeyCode struct
zip = "0.4"

vulkano = { git = "https://github.com/rukai/vulkano", branch = "fix_cpu_pool_conflict_key", optional = true }
vulkano-win = { git = "https://github.com/rukai/vulkano", branch = "git_winit_alt", optional = true }
vulkano-shader-derive = { git = "https://github.com/rukai/vulkano", branch = "fix_cpu_pool_conflict_key", optional = true }
vulkano_text = { git = "https://github.com/rukai/vulkano-text", branch = "rukai", optional = true }
cgmath = { version = "0.16", optional = true }

[features]
default = ["vulkan"]
vulkan = ["vulkano", "vulkano-win", "vulkano-shader-derive", "vulkano_text", "cgmath"]
