cargo-features = ["default-run"]

[package]
name = "pf_sandbox"
version = "0.1.1"
authors = ["Rukai <rubickent@gmail.com>"]
description = "A platform fighter sandbox featuring a character editor tightly integrated with gameplay."
license = "GPL-3.0"
repository = "https://github.com/rukai/pf_sandbox"
homepage = "https://pfsandbox.net"
keywords = ["pf", "sandbox", "platform", "fighter", "game"]
categories = ["games", "game-engines"]
default-run = "pf_sandbox"

[dependencies]
pf_sandbox_lib = { path = "../pf_sandbox_lib" }
byteorder = "1"
chrono = { version = "0.4", features = ["serde"] }
enum_traits = "0.3"
enum_traits_macros = "2.0"
getopts = "0.2"
#gilrs = "0.7"
gilrs = { git = "https://gitlab.com/gilrs-project/gilrs" }
libusb = "0.3"
log = "0.4"
lyon = "0.11"
rand = "0.5"
serde = "1"
serde_derive = "1"
serde_json = "1"
treeflection = "0.1"
treeflection_derive = "0.3"
winit = "0.17" # Needed on all builds, game logic is dependent on VirtualKeyCode struct

vulkano = { version = "0.10", optional = true }
vulkano-win = { version = "0.10", optional = true }
vulkano-shader-derive = { version = "0.10", optional = true }
vulkano_text = { version = "0.8", optional = true }
cgmath = { version = "0.16", optional = true }

[features]
default = ["vulkan"]
vulkan = ["vulkano", "vulkano-win", "vulkano-shader-derive", "vulkano_text", "cgmath"]
