[package]
name = "pf_sandbox"
version = "0.1.1"
authors = ["Rukai <rubickent@gmail.com>"]
description = "A platform fighter sandbox featuring a character editor tightly integrated with gameplay."
license = "GPL-3.0"
repository = "https://github.com/rukai/pf_sandbox"
keywords = ["pf", "sandbox", "platform", "fighter"]

[dependencies]
rand = "0.3"
chrono = { version = "0.4", features = ["serde"] }
enum_traits = "0.3"
enum_traits_macros = "2.0"
getopts = "0.2"
libusb = "0.3"
matches = "0.1.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
treeflection = "0.1"
treeflection_derive = "0.1"
rust-crypto = "0.2"
zip = "0.2"
reqwest = "0.7"
winit = "0.7" # Needed on all builds, game logic is dependent on VirtualKeyCode struct

vulkano = { version = "0.6", optional = true }
vulkano-win = { version = "0.6", optional = true }
vulkano-shader-derive = { version = "0.6", optional = true }
vulkano_text = {version = "0.4", optional = true }
glium = { version = "0.16", optional = true }

[features]
default = ["vulkan"]
vulkan = ["vulkano", "vulkano-win", "vulkano-shader-derive", "vulkano_text"]
opengl = ["glium"] # opengl is now broken, need to port it over to winit instead of glutin
