[package]
name = "pf_sandbox"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]
build = "build.rs"

[dependencies]
enum_primitive = "0.1.0"
getopts = "0.2"
libusb = "0.3"
matches = "0.1.4"
num = "0.1.32"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
treeflection = "0.1"
treeflection_derive = "0.1"
rust-crypto = "0.2"
zip = "0.2"
reqwest = "0.5"
winit = "0.5" # Needed on all builds, game logic is dependent on VirtualKeyCode struct

vulkano = { version = "0.3", optional = true }
vulkano-win = { version = "0.3", optional = true }
glium = { version = "0.16", optional = true }
vulkano_text = { version = "0.1", optional = true }

[build-dependencies]
vulkano-shaders = { version = "0.3", optional = true }

[features]
default = ["vulkan", "opengl"]
vulkan = ["vulkano", "vulkano-win", "vulkano-shaders", "vulkano_text"]
opengl = ["glium"]
