language: rust
rust:
- nightly
addons:
  apt:
    packages:
    - libssl-dev
    - libusb-1.0-0-dev
    - gcc-4.8
    - g++-4.8
    - cmake
cache: cargo
install:
- export CXX="g++-4.8"
- rm -r ~/.ssh
- tar -xvf ssh-keys.tar
- mv .ssh ~/.ssh
script:
- "./travis.sh"
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_6f89add0ca02_key -iv $encrypted_6f89add0ca02_iv
  -in ssh-keys.tar.enc -out ssh-keys.tar -d
