environment:
  global:
    RUST_VERSION: nightly
  matrix:
    - TARGET: x86_64-pc-windows-gnu

image: Visual Studio 2015

install:
    # setup ssh keys
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt ssh-keys-appveyor.zip.enc -secret %ssh-keys-secret%
  - 7z x ssh-keys-appveyor.zip
  - rm -r C:/Users/appveyor/.ssh
  - mv .ssh C:/Users/appveyor/
    # setup rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
  # setup libusb
  - set PATH=%PATH%;C:\msys64\mingw64\bin # access libusb
  - set PATH=%PATH%;C:\msys64\usr\bin # access pacman
  - echo %PATH%
  - pacman --noconfirm -Syu
  - pacman --noconfirm -Syu
  - pacman --noconfirm -Syu mingw64/mingw-w64-x86_64-pkg-config mingw64/mingw-w64-x86_64-libusb mingw-w64-x86_64-gcc mingw-w64-x86_64-gtk3

test_script:
  - cargo test --release --all
  - cargo build --release --all
  - mkdir pf\tools
  - move target\release\pf_sandbox.exe pf
  - move target\release\pf_tas.exe pf\tools
  - move target\release\pf_cli.exe pf\tools
  - move target\release\pf_map_controllers.exe pf\tools
  - copy C:\msys64\mingw64\bin\libusb-1.0.dll pf
  - copy C:\msys64\mingw64\bin\libglib-2.0-0.dll pf\tools
  - copy C:\msys64\mingw64\bin\libcairo-2.dll pf\tools
  - copy C:\msys64\mingw64\bin\libgdk-3-0.dll pf\tools
  - copy C:\msys64\mingw64\bin\libgobject-2.0-0.dll pf\tools
  - 7z a pfsandbox-%APPVEYOR_REPO_COMMIT:~0,15%-windows.zip pf
  - echo put pfsandbox-%APPVEYOR_REPO_COMMIT:~0,15%-windows.zip /home/rubic/PF_Sandbox_Website/builds/ | sftp rubic@pfsandbox.net

skip_tags: true
cache:
  - C:\Users\appveyor\.cargo\registry
# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
