[workspace]
members = [
    "pf_sandbox",
    "pf_tas",
    "pf_cli",
    "map_controllers"
]

[profile.release]
#debug-assertions = true # vulkano has invalid debug_asserts and I cant upstream the fixes ;-;
