[workspace]
members = [
    "pf_sandbox",
    "pf_tas",
    "pf_cli",
    "map_controllers"
]

[patch.crates-io]
gilrs = { git = "https://gitlab.com/rukai/gilrs", branch = "pf_sandbox2" }

[profile.release]
debug-assertions = true
