[package]
name = "pf_map_controllers"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]
edition = "2018"

[dependencies]
gtk = "0.7"
gdk = "0.11"
gilrs-core = "0.2"
pf_sandbox_lib = { path = "../pf_sandbox_lib" }
serde_json = "1.0"
uuid = { version = "0.7", features = ["v4", "serde"] }
