[package]
name = "pf_map_controllers"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]

[dependencies]
gdk = "0.7"
gilrs = "0.5"
serde_json = "1.0"
gtk = { version = "0.3", features = ["v3_12"] }
uuid = { version = "0.5", features = ["v4"] }
pf_sandbox = { path = "../pf_sandbox" }
