[package]
name = "pf_tas"
version = "0.1.1"
authors = ["Rukai <rubickent@gmail.com>"]
description = "TAS tool for PF sandbox"
license = "GPL-3.0"
repository = "https://github.com/rukai/pf_sandbox"
keywords = ["pf", "sandbox", "TAS"]

[dependencies]
winit = "0.11"
vulkano = "0.7"
vulkano-shader-derive = "0.7"
vulkano-win = "0.8"
#vulkano_text = { version = "0.6" }
vulkano_text = { version = "0.6", git = "https://github.com/rukai/vulkano-text", branch = "pf_sandbox" } # temp while waiting on next vulkano release
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"

[build-dependencies]
vulkano-shaders = "0.7"
