[package]
name = "panic_handler"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]
edition = "2018"

[dependencies]
gtk = { version = "0.6" }
pf_sandbox_lib = { path = "../pf_sandbox_lib" }
