[package]
name = "panic_handler"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]

[dependencies]
gtk = { version = "0.5", features = ["v3_12"] }
pf_sandbox_lib = { path = "../pf_sandbox_lib" }
